name: CI

on:
  pull_request:
    types:
      - opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        echo base is: $(jq --raw-output .pull_request.base.sha "${{ github.event_path }}")
        echo head is: $(jq --raw-output .pull_request.head.sha "${{ github.event_path }}")
